name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main  # अगर आपकी ब्रांच का नाम master है, तो यहाँ master लिख दें
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KRISHIPRABANDHANNEW }}
          projectId: krishiprabandhannew
          channelId: live
